name: tl_getx
description: getx 本地使用函数封装
version: 1.0.8
homepage: https://dentafilm.com
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.20.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^5.0.0
dev_dependencies: 
  flutter_test:
    sdk: flutter
flutter: null

dependency_overrides: 
  get: 
    git: 
      url: https://github.com/SakurasDuck/getx
      ref: master
